### ISSUE TITLE
archive due to inactivity & very outdated deps

### ISSUE THREAD

**Issue by ungoldman** [hypermodules/electron-repl#2]
There are some "Known security vulnerabilities detected" dependabot alerts for this repo. As it's been five years since it's been updated, it was a very experimental alpha quality project, and it's way behind on the electron version, I'm partial to just archiving the repo.

@bcomnes any thoughts or objections?

**Comment by bcomnes** [comment]
Yeah sounds good. I also wanted to float some ideas in general about winding down hypermodules. I'll write up ideas soon.
